### ISSUE TITLE
ToDo: BotHATTwaffle 2.0 Feature List

### ISSUE THREAD

**Issue by tophattwaffle** [source-engine-discord/BotHATTwaffle2#1]
BotHATTwaffle 2.0 Feature List
- [x] If no playtest exists, no message in Announcements
- [x] Make Announcement system suck way less
- [x] Port over required permissions reply for commands
- [x] LiteDB
- [x] Workshop Embed
    - [x] Line count
    - [x] Make not crash on Steam screenshot
    - [x] Update regex to work with this link https://steamcommunity.com/sharedfiles/filedetails/?id=483373394&searchtext=
- [ ] Let bot scheduled playtests instead of manual creation
- [ ] New playtest submitted message
- [x] Non-blocking Scheduling - No more 1 minute timer
    - [x] https://www.quartz-scheduler.net/
    - [x] https://github.com/HangfireIO/Hangfire
- [ ] >schedule to allow the bot to put events on the calendar. Think this command through before creating. Will need the Google sheets API
- [x] Competitive Testing
    - [x] All servers have a password always. Casual password is "sourceengine"
    - [x] Players Join Level Testing voice.
    - [x] change server password to some random value
    - [x] Provide server password for comp in that channel.
- [x] Playtest announcement message support multiple creators
- [x] rcon / play testing quick commands
- [x] Check for entire day events. Respond correctly
- [x] Playtest demo download and delivery
- [ ] Add summaries and remarks to commands and their variables
- [x] Rotating Messages for playing
    - [x] One to display number of playtests played
    - [x] >help
    - [x] >about
- [x] Update command handling for listening to all messages to be more like BHW1
- [x] Auto responses for morons
- [x] Format competitive tester channel messages to use embeds instead of code blocks
- [x] Put >rcon command replies into a nice embed
- [ ] PublicDemo - Streamline tv_record demos for community tests and retrieval of demos.
    - [ ] Start
    - [ ] Get
- [ ] Database backup
- [ ] Auto response strings in settings file
- [ ] Port Commands from old bot
    - [x] >Active
    - [x] >EditServers (Improve!)
    - [x] >Mute
    - [x] >MuteHistory
    - [x] >Playtest
    - [x] >Rcon
        - [x] Rcon system for each server, or some system where we can just type the rcon command without >rcon [server]
    - [ ] >Search (Improve!)
    - [ ] >Tutorials (Improve!)
    - [x] >VDC
    - [x] >Playtester
    - [x] >PublicAnnounce(Improve, restrict to bot only. Limit use)
    - [x] >PublicCommand
    - [x] >PublicServer
    - [x] >ReleaseServer
    - [x] >Servers
    - [x] >ShowReservations
    - [x] >ClearReservations
    - [x] >BSPsource
    - [x] >GCFScape
    - [x] >Log
    - [x] >VIDE
    - [x] >VMTEditor
    - [x] >VTFEdit
    - [x] >Wallworm

**Comment by tophattwaffle** [comment]
Creating new post launch list.
