### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tophattwaffle** [source-engine-discord/BotHATTwaffle2#20]
- [x] Make >active a toggle like >comp
- [x] Add current CT time to pts message.
- [x] Include stats in >about
- [x] regex out and put in channel name in mute reasons and replies.
- [x] Make relevant commands work in game after steam ID to discord user mapping works
- [x] Add command to link steam ID to discord account
- [x] Fix announcement messages to display creators better. Don't use Mentions
- [x] Make sure tv enable is in server config
- [x] Move auto convert into a single command
- [x] Add word date to pts true
- [x] >request tells you to go to a link, but no link is sent
- [x] Make sure that >p post resets password on map change
- [x] Make >pc work ingame chat

**Comment by tophattwaffle** [comment]
All things donezoe!
