### ISSUE TITLE
Post Launch Todo list

### ISSUE THREAD

**Issue by tophattwaffle** [source-engine-discord/BotHATTwaffle2#4]
- [x] Allow for logging feedback mid playtest, establish rcon connection and listen to event?
- [x] PublicDemo - Streamline tv_record demos for community tests and retrieval of demos.
    - [x] Start
    - [x] Get
- [x] >pts should not give the user options if queue is empty
- [x] >t needs to be re-added
